### ISSUE TITLE
Trader

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#23]
operation is taking place successfully, but it turns out that an error code

Notice: Undefined index: crystal in /home/eskiog/public_html/beta6/application/controllers/game/trader.php on line 267

Notice: Undefined index: metal in /home/eskiog/public_html/beta6/application/controllers/game/trader.php on line 267

Notice: Undefined index: deuterium in /home/eskiog/public_html/beta6/application/controllers/game/trader.php on line 267

**Comment by athk** [comment]
Seems like it's a wrong index that could cause issues with reaching max storage capacity

**Comment by BeReal86** [comment]
The maximum storage capacity was not. It had pretty much space

**Comment by athk** [comment]
Yep, yep. I'm saying it could cause some checks to return incorrect values if the player was near or at max storage capacity.

For example, try (without the fix) setting your metal and crystal to maximum storage capacity. Then try to get some metal (or crystal) from the trader. It will let you perform the exchange, but it should not.

This should be fixed with the PR though, it's a minor mistake.

**Comment by BeReal86** [comment]
Thank you for the explanation now better understood
